# -*- coding: utf-8 -*-
"""Automated Report Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYlpFv7NjHDIs73UeA254L2_6cl-uNmc
"""

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.platypus import Table, TableStyle, SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def generate_report(data_file, output_pdf):
    df = pd.read_csv(data_file)
    summary = df.describe(include='all').fillna("").round(2)
    department_counts = df['Department'].value_counts().reset_index()
    department_counts.columns = ['Department', 'Count']

    doc = SimpleDocTemplate(output_pdf, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Employee Data Report", styles['Title']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Summary Statistics", styles['Heading2']))
    data_summary = [summary.columns.tolist()] + summary.values.tolist()
    t1 = Table(data_summary)
    t1.setStyle(TableStyle([("GRID", (0,0), (-1,-1), 0.5, colors.grey)]))
    story.append(t1)
    story.append(Spacer(1, 24))

    story.append(Paragraph("Employees per Department", styles['Heading2']))
    data_dept = [department_counts.columns.tolist()] + department_counts.values.tolist()
    t2 = Table(data_dept)
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black)
    ]))
    story.append(t2)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Generated using Python and ReportLab", styles['Normal']))

    doc.build(story)

if __name__ == "__main__":
    generate_report("sample_data.csv", "report.pdf")